use serde::Deserialize;

#[derive(Debug, Clone, Deserialize)]
#[allow(dead_code)]
pub struct SourceResource {
    pub id: String,
    #[serde(rename = "type")]
    pub resource_type: Option<String>,
    pub attributes: SourceAttributes,
}

#[derive(Debug, Clone, Deserialize)]
#[allow(dead_code)]
pub struct SourceAttributes {
    pub name: Option<String>,
    pub platform: Option<String>,
    pub table_name: Option<String>,
    pub token: Option<String>,
    pub ingesting_paused: Option<bool>,
    pub live_tail_url: Option<String>,
    pub retention: Option<u32>,
    pub created_at: Option<String>,
    pub updated_at: Option<String>,
    pub logs_count: Option<u64>,
    pub logs_bytes: Option<u64>,
    pub autogenerated_views: Option<Vec<serde_json::Value>>,
}
