use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Deserialize)]
#[allow(dead_code)]
pub struct SourceResource {
    pub id: String,
    #[serde(rename = "type")]
    pub resource_type: Option<String>,
    pub attributes: SourceAttributes,
}

#[derive(Debug, Clone, Deserialize)]
#[allow(dead_code)]
pub struct SourceAttributes {
    pub team_id: Option<u64>,
    pub name: Option<String>,
    pub platform: Option<String>,
    pub table_name: Option<String>,
    pub token: Option<String>,
    pub ingesting_paused: Option<bool>,
    pub live_tail_url: Option<String>,
    pub live_tail_pattern: Option<String>,
    pub retention: Option<u32>,
    pub logs_retention: Option<u32>,
    pub metrics_retention: Option<u32>,
    pub vrl_transformation: Option<String>,
    pub created_at: Option<String>,
    pub updated_at: Option<String>,
    pub logs_count: Option<u64>,
    pub logs_bytes: Option<u64>,
    pub autogenerated_views: Option<Vec<serde_json::Value>>,
}

#[derive(Debug, Default, Serialize)]
pub struct SourceUpdate {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ingesting_paused: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub logs_retention: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metrics_retention: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub live_tail_pattern: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub vrl_transformation: Option<String>,
}
